server:
  port: 8000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true

spring:
  application:
    name: apigateway-service
  cloud:
    gateway:
      default-filters:
        - name: GlobalFilter
      routes:
        - id: user-service
          predicates:
            - Path=/user-service/**
          uri: lb://USER-SERVICE
          filters:
            - RewritePath=/first-service/(?<segment>.*), /$\{segment}